name: Build and deploy spring app

on:
  push:
    branches:
      - main
      
      
jobs:
  build-deploy:
    name: Build and deploy spring boot for beginners
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v3


      - name: setup java jdk 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Unit test
        run: mvn -B test --file pom.xml


      - name: Build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml
          
      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-for-beginners:latest
       
      - name: login to dockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}    

      - name: Push Docker Image
        uses: action/build-push-docker-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-for-beginners:latest