name: Build and deploy spring app

on:
  push:
    branches:
      - main
      
      
jobs:
  build-deploy:
    name: Build and deploy spring boot for beginners
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v3


      - name: setup java jdk 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Unit test
        run: mvn -B test --file pom.xml


      - name: Build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml
            

